title: RawStor Benchmark
description: Performance test results

# Разрешаем обработку HTML файлов
include: ['*.html', '*.js', '*.css']

# Настройки для Jekyll
exclude: ['frontend/', 'tools/', 'data/']